### ISSUE TITLE
gobuster

### ISSUE THREAD

**Issue by trevorbryant** [trevorbryant/ansible-playbooks#23]
There doesn't seem to be an easy Ansible way of downloading [gobuster](https://github.com/OJ/gobuster) without custom commands.

Will need to research and install manually for now. The package in `apt` is out of date.

**Comment by iAmG-r00t** [comment]
Install it using go get from shell :)

**Comment by trevorbryant** [comment]
I was thinking about doing that though it seems janky. But, if it works, it works!

**Comment by trevorbryant** [comment]
@iAmG-r00t looks like something I can borrow from here to make it work.

http://clouds.freeideas.cz/subdom/clouds/2017/08/02/ansible-install-golang-and-set-env-variables/

**Comment by trevorbryant** [comment]
Resolved with https://github.com/trevorbryant/desktop/pull/24.
